name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"

inputs:
  source-path:
    description: "Source Path from Git Root"
    default: .

runs:
  - name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run scan --srcDir "${{inputs.source-path}}" --outputDir "./my-output-path" --format "json"

