name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"

inputs:
  source-path:
    description: "Source Path from Git Root"
    default: .


runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
      shell: bash
      - run: npm run scan --srcDir "${{inputs.source-path}}" --outputDir "./my-output-path" --format "json"

