name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"
inputs:
  source-path:
    description: "Source Path from Git Root"
    required: true
    default: .
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Echo test
      run: echo test
      shell: bash

    - name: List files
      run: ls
      shell: bash

    - name: Check Node.js version
      run: node --version
      shell: bash
