name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"
inputs:
  source-path:
    description: "Source Path from Git Root"
    required: true
    default: .
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: some step
      shell: bash
    - run: echo test
    - run: ls
    - run: node --version
