name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"
inputs:
  source-path:
    description: "Source Path from Git Root"
    required: true
    default: .
  project-name:
    description: "Project name"
    required: true
    default: .

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install Graphviz
      run: |
        sudo apt update
        sudo apt install -y graphviz
      shell: bash

    - name: Install dependecies
      run: cd ${{ github.action_path }}/scripts/complexity && npm install
      shell: bash

    - name: Running complexity metrics
      run: node ${{ github.action_path }}/scripts/complexity/src/index.js --srcDir "./" --outputDir "./report" --format "json"  && echo "Composed metrics results written to  ./metric.json"
      shell: bash

    - name: Collecting metrics
      run: node ${{ github.action_path }}/scripts/compose/index.js --path ./sonar-mymetrics.json --output . --complexityReportPath ${{ github.workspace }} --branchName ${{ github.ref_name }} && echo "Collected metrics results written to  ./metric.json"
      shell: bash

    - name: Show metrics
      run: cat ./metrics.json
      shell: bash

    - name: Sending metrics
      run: node ${{ github.action_path }}/scripts/send/index.js --projectName ${{inputs.project-name}} --metrics ./metrics.json
      shell: bash
