name: "Quality Metter"
description: "Quality Scan GitHub Action for JS/TS files"
author: "jhersonharyson"
inputs:
  source-path:
    description: "Source Path from Git Root"
    required: true
    default: .
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Echo test
      run: echo test
      shell: bash

    - name: Install dependecies
      run: cd ${{ github.action_path }}/scripts/complexity npm install
      shell: bash

    - name: Running complexity metrics
      run: node ${{ github.action_path }}/scripts/complexity/src/index.js --srcDir "./" --outputDir "./report" --format "json"  && echo "Compose metrics results written to  ./metric.json"
      shell: bash

    - name: Collecting metrics
      run: node ${{ github.action_path }}/scripts/compose/index.js --path ./sonar-mymetrics.json --output . && echo "Compose metrics results written to  ./metric.json"
      shell: bash

    - name: List files
      run: ls
      shell: bash
